import Head from "next/head";
import classes from "../styles/Home.module.css";
import Welcome from "../components/Welcome/Welcome";
import What from "../components/What/What";
import About from "../components/About/About";
import Projects from "../components/Projects/Projects";

export default function Home() {
  return (
    <div className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.main}>
        <Welcome />
        <About />
        <What />
        <Projects />
      </main>
    </div>
  );
}
